name: Deploy SQL Server Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub (or your container registry)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t my-sql-server-image .
          docker tag my-sql-server-image:latest ${{ secrets.DOCKER_USERNAME }}/my-sql-server-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-sql-server-image:latest

      - name: Deploy SQL Server container
        run: |
          docker run -d --name sql0 -p 1433:1433 ${{ secrets.DOCKER_USERNAME }}/my-sql-server-image:latest
